name: CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  infra-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Assume Role via OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.IAM_ROLE_ARN_OIDC_GITHUB }}
          role-session-name: Github-Actions
          aws-region: ${{ env.AWS_REGION }}

      - name: Pulumi installation
        run: |
          curl -fsSL https://get.pulumi.com | sh
          export PATH=$PATH:/root/.pulumi/bin

      - name: Pulumi Login using S3 as backend
        run: pulumi login ${{ env.IAM_ROLE_ARN_OIDC_GITHUB }}

      - name: Pulumi Preview
        run: pulumi preview --diff --refresh

      - name: Pulumi Deploy
        run: pulumi up --yes --refresh
